# Generated by Django 4.2.7 on 2024-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0002_order_transaction_id_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('pink', 'Pink'), ('red', 'Red'), ('blue', 'Blue'), ('gray', 'Gray'), ('black', 'Black'), ('green', 'Green'), ('purple', 'Purple')], max_length=50),
        ),
    ]
