# Generated by Django 4.2.7 on 2024-01-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=100),
        ),
    ]
