# Generated by Django 4.2.7 on 2024-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='password1',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
