# Generated by Django 4.2.7 on 2024-01-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0006_remove_customer_user_customer_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password2',
            field=models.IntegerField(null=True),
        ),
    ]
