# Generated by Django 4.2.7 on 2024-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0008_alter_customer_password1_alter_customer_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
