# Generated by Django 4.2.7 on 2024-01-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0010_remove_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
