# Generated by Django 4.2.7 on 2024-01-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0014_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlclothing.order'),
        ),
    ]
