# Generated by Django 4.2.7 on 2024-01-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0015_remove_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='order_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='rlclothing.order'),
        ),
    ]
