# Generated by Django 4.2.7 on 2024-01-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0016_alter_shippingaddress_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order_name',
            new_name='ordername',
        ),
    ]
