# Generated by Django 4.2.7 on 2024-01-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0018_rename_ordername_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapproval',
            name='available_orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='rlclothing.order'),
        ),
    ]
