# Generated by Django 4.2.7 on 2024-01-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0022_alter_orderapproval_available_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapproval',
            name='available_orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderapprove', to='rlclothing.order'),
        ),
    ]
