# Generated by Django 4.2.7 on 2024-01-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlclothing', '0026_rename_order_orderapproval_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapproval',
            name='order_name',
        ),
        migrations.AddField(
            model_name='orderapproval',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='rlclothing.order'),
        ),
    ]
